// <auto-generated />
using June2023_technical.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace June2023_technical.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("June2023_technical.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            Price = 10.99m,
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            Price = 9.99m,
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            Price = 12.99m,
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            Price = 14.99m,
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            Price = 15.99m,
                            PublicationYear = 1851,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Leo Tolstoy",
                            Genre = "Historical Fiction",
                            Price = 20.99m,
                            PublicationYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            Price = 10.99m,
                            PublicationYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Price = 13.99m,
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Philosophical Fiction",
                            Price = 16.99m,
                            PublicationYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Philosophical Fiction",
                            Price = 18.99m,
                            PublicationYear = 1880,
                            Title = "The Brothers Karamazov"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
